---
- hosts: AD
  tasks: 
  - name: Copy Notepad from source to destination location
    win_copy: 
      src: C:\src\notepad.zip
      dest: c:\dest
      remote_src: yes
  - name: Unzip the file
    win_unzip: 
       src: C:\dest\notepad.zip
       dest: c:\
  - name: Install Notepad
    ansible.windows.win_package: 
      path: c:\notepad.exe
      state: present